### ISSUE TITLE
 有些执行问题想请教一下

### ISSUE THREAD

**Issue by wsglc** [zzzzer91/douyu_dm#3]
Traceback (most recent call last):
  File "D:\1.py", line 118, in <module>
    main()
  File "D:\1.py", line 105, in main
    room_id, name = get_room_info(uid)
  File "D:\1.py", line 39, in get_room_info
    name = pattern.findall(r.text)[0]
IndexError: list index out of range
原样复制之后输入一个uid就这样 百思不得奇解，希望能得到指导。

**Comment by zzzzer91** [comment]
抱歉 github貌似没消息提醒? 现在才看到, 刚看了下, 貌似是类名改了, 已修正.

**Comment by wsglc** [comment]
谢,辛苦了 已ok

**Comment by wsglc** [comment]
谢,辛苦了 已ok
